"use strict";
const C=window.NYJ20_CONFIG||{},URLX=String(C.appsScriptUrl||'');const $=s=>document.querySelector(s);let data=null,selected=1,editorNo=1,imgData='',imgAction='keep';
const token=localStorage.getItem('nyj20_admin_session_token_v3')||'',station=localStorage.getItem('nyj20_admin_station_v3')||'마블룰렛 무대';
function toast(x){const t=$('#toast');t.textContent=x;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),3800)}
function loading(on,text=''){if(text)$('#loadingText').textContent=text;$('#loading').classList.toggle('hidden',!on)}
function reqId(){return'r_'+Date.now()+'_'+Math.random().toString(36).slice(2)}
function api(action,payload={}){return new Promise((resolve,reject)=>{if(!token)return reject(new Error('관리자 페이지에서 먼저 로그인해 주세요.'));const id=reqId(),frame=document.createElement('iframe'),form=document.createElement('form');frame.name='f_'+id;frame.style.display='none';form.method='POST';form.action=URLX;form.target=frame.name;form.style.display='none';for(const[k,v]of Object.entries({bridge:'1',requestId:id,action,token,station,payload:JSON.stringify(payload)})){const i=document.createElement('input');i.type='hidden';i.name=k;i.value=v;form.append(i)}document.body.append(frame,form);const deadline=Date.now()+(Number(C.requestTimeoutMs)||40000);let sc,cb;const clean=()=>{if(sc)sc.remove();if(cb)try{delete window[cb]}catch(_){}form.remove();setTimeout(()=>frame.remove(),50)};const poll=()=>{if(Date.now()>deadline){clean();return reject(new Error('서버 응답 시간이 초과되었습니다.'))}cb='__p'+Date.now()+Math.random().toString(36).slice(2);const u=new URL(URLX);u.searchParams.set('action','bridgePoll');u.searchParams.set('requestId',id);u.searchParams.set('callback',cb);u.searchParams.set('_',Date.now());sc=document.createElement('script');window[cb]=r=>{sc.remove();sc=null;if(r?.pending)return setTimeout(poll,220);clean();if(!r?.ok)return reject(new Error(r?.error||'서버 오류'));resolve(r.data)};sc.onerror=()=>{sc.remove();sc=null;setTimeout(poll,350)};sc.src=u;document.head.append(sc)};form.submit();setTimeout(poll,180)})}
function prize(){return data?.prizes?.find(p=>p.prizeNo===selected)}
function render(){if(!data)return;$('#arrived').textContent=data.arrivedCount;$('#eligible').textContent=data.eligibleCount;$('#excluded').textContent=data.excludedWinnerCount;$('#connection').textContent='준비실 연결됨';$('#prizes').innerHTML=data.prizes.map(p=>`<button class="prize ${p.prizeNo===selected?'active':''}" data-p="${p.prizeNo}"><b>${p.prizeNo}번</b><small>${p.prizeName||'미설정'} · 남음 ${p.remaining}</small></button>`).join('');const p=prize();$('#selected').innerHTML=p?`<b>${p.prizeNo}번 · ${p.prizeName||'미설정'}</b> · 총 ${p.quantity} / 남음 ${p.remaining}`:'상품을 선택하세요';$('#winnerCount').max=Math.max(1,Math.min(p?.remaining||1,data.eligibleCount||1));renderEditorSlots()}
async function load(){loading(true,'도착 참가자와 상품을 한 번에 불러오는 중입니다.');try{data=await api('rouletteBootstrap');if(!data.prizes.some(p=>p.prizeNo===selected&&p.active&&p.remaining>0))selected=(data.prizes.find(p=>p.active&&p.remaining>0)||data.prizes[0]).prizeNo;render()}finally{loading(false)}}
function renderEditorSlots(){if(!data)return;$('#editorSlots').innerHTML=data.prizes.map(p=>`<button class="prize ${p.prizeNo===editorNo?'active':''}" data-e="${p.prizeNo}"><b>${p.prizeNo}</b><small>${p.prizeName||'미설정'}</small></button>`).join('')}
async function edit(no){editorNo=Number(no);imgAction='keep';imgData='';renderEditorSlots();const p=data.prizes.find(x=>x.prizeNo===editorNo);$('#productName').value=p.prizeName||'';$('#productQty').value=p.quantity||0;$('#productNote').value=p.note||'';$('#productActive').checked=!!p.active;$('#preview').innerHTML='';if(p.hasImage){try{const r=await api('roulettePrizeImage',{prizeNo:editorNo});if(r.imageDataUrl){imgData=r.imageDataUrl;$('#preview').innerHTML=`<img src="${imgData}">`}}catch(_){}}}
async function compress(file){const u=URL.createObjectURL(file);try{const im=await new Promise((r,j)=>{const i=new Image;i.onload=()=>r(i);i.onerror=j;i.src=u});const scale=Math.min(1,420/Math.max(im.naturalWidth,im.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(im.naturalWidth*scale);c.height=Math.round(im.naturalHeight*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.74)}finally{URL.revokeObjectURL(u)}}
async function saveProduct(){loading(true,'상품을 저장하는 중입니다.');try{await api('saveRoulettePrize',{prizeNo:editorNo,prizeName:$('#productName').value,quantity:Number($('#productQty').value)||0,note:$('#productNote').value,active:$('#productActive').checked,imageAction:imgAction,imageDataUrl:imgAction==='replace'?imgData:''});await load();toast('상품을 저장했습니다.')}finally{loading(false)}}
async function prepare(){const p=prize(),count=Math.max(1,Number($('#winnerCount').value)||1);if(!p?.active||!p.prizeName)return toast('사용할 상품을 선택해 주세요.');if(count>p.remaining||count>data.eligibleCount)return toast('당첨 인원 또는 상품 수량을 확인해 주세요.');loading(true,'현장용 추첨 데이터를 미리 저장하고 있습니다.');try{const mode=$('#winnerMode').value,plan=await api('prepareRouletteRound',{prizeNo:p.prizeNo,winnerCount:count,winnerMode:mode});let image='';if(p.hasImage){try{image=(await api('roulettePrizeImage',{prizeNo:p.prizeNo})).imageDataUrl||''}catch(_){}}const participantMap={};data.participants.forEach(x=>participantMap[x.seat]=x);const snap={version:2,preparedAt:new Date().toISOString(),plan,participantMap,prizeImage:image,mapIndex:Number($('#mapIndex').value)||0,speed:Number($('#speed').value)||1.15,skills:$('#skills').checked};localStorage.setItem('nyj20.marbleStageSnapshot.v2',JSON.stringify(snap));$('#snapshot').textContent=`준비 완료 · ${plan.poolCount}개 구슬 · ${p.prizeName} · ${count}명 · ${mode==='last'?'꼴찌':'1등'} 기준`;$('#openStage').disabled=false;toast('현장용 데이터 준비 완료')}finally{loading(false)}}
function maps(){const titles=['핀볼','지그재그','회전 장애물','미로','낙하 장애물','랜덤 코스','코스 7','코스 8','코스 9','코스 10'];$('#mapIndex').innerHTML=titles.map((t,i)=>`<option value="${i}">${i+1}. ${t}</option>`).join('')}
function bind(){maps();$('#refresh').onclick=()=>load().catch(e=>toast(e.message));$('#prizes').onclick=e=>{const b=e.target.closest('[data-p]');if(b){selected=Number(b.dataset.p);render()}};$('#toggleEditor').onclick=()=>{$('#editor').classList.toggle('hidden');edit(selected)};$('#editorSlots').onclick=e=>{const b=e.target.closest('[data-e]');if(b)edit(b.dataset.e)};$('#productImage').onchange=async e=>{const f=e.target.files?.[0];if(f){imgData=await compress(f);imgAction='replace';$('#preview').innerHTML=`<img src="${imgData}">`}};$('#removeImage').onclick=()=>{imgData='';imgAction='remove';$('#preview').innerHTML='사진 없음'};$('#saveProduct').onclick=()=>saveProduct().catch(e=>toast(e.message));$('#prepareStage').onclick=()=>prepare().catch(e=>toast(e.message));$('#openStage').onclick=()=>window.open('./stage.html','marble_stage');const saved=localStorage.getItem('nyj20.marbleStageSnapshot.v2');if(saved){try{const s=JSON.parse(saved);$('#snapshot').textContent=`저장된 준비본 있음 · ${s.plan.poolCount}개 구슬 · ${s.plan.prize.prizeName}`;$('#openStage').disabled=false}catch(_){}}}
document.addEventListener('DOMContentLoaded',()=>{bind();load().catch(e=>toast(e.message))});
