import {Roulette} from './original-engine/roulette.js';import options from './original-engine/options.js';
const $=s=>document.querySelector(s),snapRaw=localStorage.getItem('nyj20.marbleStageSnapshot.v2');let snap=null,roulette=null,finished=[],pendingWinners=[];
try{snap=JSON.parse(snapRaw||'null')}catch(_){snap=null}
const C=window.NYJ20_CONFIG||{},API=String(C.appsScriptUrl||''),token=localStorage.getItem('nyj20_admin_session_token_v3')||'',station=localStorage.getItem('nyj20_admin_station_v3')||'마블룰렛 무대';
function bridge(action,payload={}){return new Promise((resolve,reject)=>{if(!token)return reject(new Error('관리자 로그인 정보가 없습니다.'));const id='s_'+Date.now()+'_'+Math.random().toString(36).slice(2),f=document.createElement('iframe'),form=document.createElement('form');f.name='f'+id;f.style.display='none';form.method='POST';form.action=API;form.target=f.name;form.style.display='none';for(const[k,v]of Object.entries({bridge:'1',requestId:id,action,token,station,payload:JSON.stringify(payload)})){const i=document.createElement('input');i.name=k;i.value=v;form.append(i)}document.body.append(f,form);let sc,cb;const deadline=Date.now()+(Number(C.requestTimeoutMs)||40000),clean=()=>{if(sc)sc.remove();if(cb)try{delete window[cb]}catch(_){}form.remove();setTimeout(()=>f.remove(),50)},poll=()=>{if(Date.now()>deadline){clean();return reject(new Error('결과 저장 시간이 초과되었습니다.'))}cb='__s'+Date.now()+Math.random().toString(36).slice(2);const u=new URL(API);u.searchParams.set('action','bridgePoll');u.searchParams.set('requestId',id);u.searchParams.set('callback',cb);u.searchParams.set('_',Date.now());sc=document.createElement('script');window[cb]=r=>{sc.remove();sc=null;if(r?.pending)return setTimeout(poll,250);clean();if(!r?.ok)return reject(new Error(r?.error||'저장 실패'));resolve(r.data)};sc.onerror=()=>{sc.remove();sc=null;setTimeout(poll,400)};sc.src=u;document.head.append(sc)};form.submit();setTimeout(poll,200)})}
function labels(){return snap.plan.ranking.map(x=>x.seat)}
function setupHud(){const p=snap.plan.prize;$('#prizeNo').textContent=`상품 ${p.prizeNo}번`;$('#prizeName').textContent=p.prizeName;$('#marbleCount').textContent=`${snap.plan.poolCount} MARBLES`;$('#modeLabel').textContent=`${snap.plan.winnerMode==='last'?'꼴찌':'1등'} 기준 ${snap.plan.winnerCount}명`;$('#readyTitle').textContent=p.prizeName;$('#readyMeta').textContent=`도착자 ${snap.plan.poolCount}명 · 구슬 ${snap.plan.poolCount}개 · ${snap.plan.winnerCount}명 당첨`}
function confetti(){const h=$('#confetti');for(let i=0;i<100;i++){const e=document.createElement('i');e.className='conf';e.style.left=Math.random()*100+'%';e.style.background=`hsl(${Math.random()*360} 90% 60%)`;e.style.setProperty('--x',(Math.random()*260-130)+'px');e.style.animationDelay=Math.random()*.8+'s';h.append(e)}setTimeout(()=>h.innerHTML='',4200)}
function winnersFromFinish(){finished=roulette.getFinishedNames();const n=snap.plan.winnerCount;if(snap.plan.winnerMode==='last')return finished.slice(-n);return finished.slice(0,n)}
function renderResult(seats){pendingWinners=seats;const rows=seats.map(seat=>snap.participantMap[seat]||{name:'참가자',organization:'',seat});$('#winners').innerHTML=rows.map((p,i)=>`<div class="winner"><b>${i+1}</b><span><strong>${p.name}</strong><small>${p.organization||''}</small></span><em>${p.seat||seats[i]}</em></div>`).join('');$('#resultPrize').textContent=snap.plan.prize.prizeName;if(snap.prizeImage)$('#resultImage').innerHTML=`<img src="${snap.prizeImage}">`;$('#result').classList.remove('hidden');confetti();saveResult()}
async function saveResult(){const s=$('#saveStatus');s.textContent='당첨 결과를 서버에 저장하고 있습니다. (화면 진행에는 영향 없음)';s.style.color='#cbd5e1';try{await bridge('commitOriginalMarbleRound',{roundToken:snap.plan.roundToken,winnerSeats:pendingWinners});s.textContent='✓ 결과 저장 완료 · QR 당첨확인과 연동되었습니다.';s.style.color='#86efac';$('#retry').classList.add('hidden')}catch(e){s.textContent='저장 실패: '+e.message;s.style.color='#fca5a5';$('#retry').classList.remove('hidden')}}
function startRace(){if(!roulette||!roulette.isReady)return;$('#readyOverlay').classList.add('hidden');options.useSkills=!!snap.skills;options.winningRank=snap.plan.winnerMode==='last'?snap.plan.poolCount-1:snap.plan.winnerCount-1;roulette.setWinningRank(options.winningRank);roulette.setSpeed(snap.speed||1.15);roulette.start()}
async function init(){if(!snap?.plan){$('#stageLoading').classList.add('hidden');$('#error').classList.remove('hidden');return}setupHud();roulette=new Roulette();const wait=()=>new Promise((res,rej)=>{const st=Date.now();const t=setInterval(()=>{if(roulette.isReady){clearInterval(t);res()}else if(Date.now()-st>25000){clearInterval(t);rej(new Error('원본 물리엔진 로딩이 지연되고 있습니다.'))}},50)});try{await wait();roulette.setTheme('dark');roulette.setMap(Math.max(0,Math.min(roulette.getMaps().length-1,snap.mapIndex||0)));roulette.setMarbles(labels());options.useSkills=!!snap.skills;roulette.addEventListener('goal',()=>{setTimeout(()=>renderResult(winnersFromFinish()),900)});$('#stageLoading').classList.add('hidden');$('#readyOverlay').classList.remove('hidden')}catch(e){$('#stageLoading').innerHTML=`<h2>원본 Marble Roulette 엔진을 불러오지 못했습니다.</h2><p>${e.message}</p><p>인터넷 연결 후 준비실에서 다시 열어주세요.</p>`}}
$('#start').onclick=startRace;addEventListener('keydown',e=>{if(e.code==='Space'&&!$('#readyOverlay').classList.contains('hidden')){e.preventDefault();startRace()}});$('#fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();$('#retry').onclick=saveResult;$('#back').onclick=()=>location.href='./';init();
